sequences_dict = {
    '20merA':'HPHPPHHPHPPHPHHPPHPH',
    '36mer' :'PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP',
    'S1'    :'HPHHPPHHHHPHHHPPHHPPHPHHHPHPHHPPHHPPPHPPPPPPPPHH',
    'S2'    :'HHHHPHHPHHHHHPPHPPHHPPHPPPPPPHPPHPPPHPPHHPPHHHPH',
    'S3'    :'PHPHHPHHHHHHPPHPHPPHPHHPHPHPPPHPPHHPPHHPPHPHPPHP'
}
